export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UsersRepository: Symbol.for('UsersRepository'),
	ProductRepository: Symbol.for('ProductRepository'),
	ProductService: Symbol.for('ProductService'),
	ProductController: Symbol.for('ProductController'),
	CategoryRepository: Symbol.for('CategoryRepository'),
	CategoryService: Symbol.for('CategoryService'),
	CategoryController: Symbol.for('CategoryController'),
	Bot: Symbol.for('Bot'),
	StartScene: Symbol.for('StartScene'),
};
